spring:
  application:
    name: cloudapigateway
  cloud:
    gateway:
      routes:

        - id: todoList
          uri: lb://todoService
          predicates:
            - Path=/task/**
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/user/**

server:
  port: 8087
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka